### ISSUE TITLE
makesignedstandardtx not adding timestamp

### ISSUE THREAD

**Issue by BigShoots** [VeriBlock/offline-wallet-cli#2]
When generating a transaction using makesignedstandardtx the tx timestamp is empty.

      "transaction": {
        "size": 62,
        "txid": "4F37A34CDBDD5D8A054140E43C7495657F8292973AA70527F7F961F02801D8BC",
        "data": "",
        "type": "standard",
        "fee": "0.00700000",
        "timestamp": 0,

**Comment by BernatCarbo** [comment]
Should be solved with https://github.com/VeriBlock/offline-wallet-cli/pull/3
